### ISSUE TITLE
prop 传参时，待符号无法正常在 class 中渲染吗？

### ISSUE THREAD

**Issue by carveybunt** [uni-helper/vite-plugin-uni-tailwind#30]
### 描述问题

```vue
<template>
<view :class="z">
</template>
</template>

<script setup lang="ts">
interface Props {
  z: string,
}

const props = withDefaults(
  defineProps<Props>(),
  {
    z: 'z-[123]',
  },
)
</script>
```

无法正常在 class 中渲染。 z 正常渲染结果为：'z--123-'，而实际得到的结果是：'z 123'。

### 复现

```vue
<template>
<view :class="z">
</template>
</template>

<script setup lang="ts">
interface Props {
  z: string,
}

const props = withDefaults(
  defineProps<Props>(),
  {
    z: 'z-[123]',
  },
)
</script>
```

### 系统信息

```Shell
vscode:1.84.2
node:18.18.0
npm:9.8.1
vue:3.3.4
vite:4.1.4
vite-plugin-uni-tailwind: 0.13.1
tailwindcss:3.3.3
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
该问题与 https://github.com/uni-helper/vite-plugin-uni-tailwind/issues/30 一致。目前 0.14.0-0 支持 string，后续会继续更新增加支持，欢迎尝试反馈，谢谢你的关注！

weapp-tailwindcss 之前有遇到过类似的问题，见 https://github.com/sonofmagic/weapp-tailwindcss/issues/140，但我个人没有尝试过 weapp-tailwindcss，不确定它是否已克服。

如果不限于 tailwindcss，可以尝试 unocss，配合 @uni-helper/unocss-preset-uni 或 unocss-applet。
