### ISSUE TITLE
a标签转换有误，在微信小程序下scoped自动生成的字符串含有a，也会转换

### ISSUE THREAD

**Issue by seepine** [uni-helper/vite-plugin-uni-tailwind#31]
### 描述问题

例如 ['a', ['functional-page-navigator', 'navigator'] 规则
当组件样式添加了scoped例如
![image](https://github.com/uni-helper/vite-plugin-uni-tailwind/assets/93666053/9439ac51-0c53-40e4-a3c8-ab31dd0a73ad)
此时小程序编译后css为
![image](https://github.com/uni-helper/vite-plugin-uni-tailwind/assets/93666053/38239c85-631c-438e-9f22-9e7985854093)
查看组件dom恰好scpoed结尾为a，`data-v-591e6b6a`
![image](https://github.com/uni-helper/vite-plugin-uni-tailwind/assets/93666053/28be1784-d1f7-40c5-a290-66e51710055a)

### 复现
如图所示

### 系统信息

```Shell
mac win都有出现
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
@seepine  感谢指出该问题！请试试 0.14.0 🙏
