### ISSUE TITLE
text-[]语法，无法解析rpx

### ISSUE THREAD

**Issue by 956632862** [uni-helper/vite-plugin-uni-tailwind#35]
### 描述问题

用了`text-[xxrpx]`没法解析出来。除非使用`text-[xx px]`才可以
<img width="501" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-tailwind/assets/33861685/07957e4b-4db8-4422-bfdd-4adfb1e6a628">

![image](https://github.com/uni-helper/vite-plugin-uni-tailwind/assets/33861685/edc6a7ad-49e1-436a-875b-360ba8cfd029)

### 复现

按照上面代码就可以复现

### 系统信息

```Shell
webstorm
node 18.19.1
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
1. 这是 tailwindcss 识别问题，本插件只负责处理 classname 不负责处理生成的样式，你可以手动写脚本处理
2. rpx 与屏幕宽度挂钩，我个人不推荐用于字体大小

参考 https://github.com/sonofmagic/weapp-tailwindcss/issues/110

**Comment by ModyQyW** [comment]
考虑未来增加支持 patch

**Comment by ModyQyW** [comment]
0.15.0
