### ISSUE TITLE
在多语义情况下，无法正确识别“rpx”

### ISSUE THREAD

**Issue by 956632862** [uni-helper/vite-plugin-uni-tailwind#36]
### 描述问题

在有多语义的情况下，传入rpx无法正确识别。
比如 text-[13rpx]，不能正确识别为 font-size:13rpx; 识别成了 color:13rpx;

### 复现

<img width="422" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-tailwind/assets/33861685/511e55aa-9332-4fb8-b81e-ab1d95675631">

### 系统信息

```Shell
webstorm 23.2
node 18.19.0
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
这是 tailwindcss 生成的问题，见 https://github.com/sonofmagic/weapp-tailwindcss/issues/110。

在 0.15.0 已经尝试修复这个问题，请尝试 0.15.0。

**Comment by ModyQyW** [comment]
https://github.com/uni-helper/vite-plugin-uni-tailwind/issues/35
