### ISSUE TITLE
使用了:class的组件编译出来的class会携带转义符号

### ISSUE THREAD

**Issue by 956632862** [uni-helper/vite-plugin-uni-tailwind#37]
### 描述问题

如果组件使用了:class，再使用tw的语法 比如 mb-[13rpx]。这样子使用之后，class会出现以下的情况导致报错
![7621715579532_ pic](https://github.com/uni-helper/vite-plugin-uni-tailwind/assets/33861685/7516b8e7-4ea0-4047-b5a4-6a040f9ca8eb)

### 复现

在组件使用了:class，再使用tw的语法 比如 mb-[13rpx]

### 系统信息

微信开发者工具 1.06

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
:class 具体是怎么用的

**Comment by tianzhich** [comment]
应该和 :class 没关系，我发现如果使用的 `leading-[32px] rounded-[32px]` 这种，编译出来的就是：

```
class="{{['px-5','py-4',\"leading--32px-\",\"rounded--32px-\",'border']}}"
```

在微信开发者工具上运行正常，但是一旦点击 remote debug，微信 compile 后会报错：

```
message：Remote Debug Error: 1:836:unexpected character `\`
```

不知道这里为啥要使用 `"` 然后再转义，如果都替换成 `'` 就没问题，好像微信 compile 的时候不让用 `\`

**Comment by ModyQyW** [comment]
> 应该和 :class 没关系，我发现如果使用的 `leading-[32px] rounded-[32px]` 这种，编译出来的就是：
> 
> ```
> class="{{['px-5','py-4',\"leading--32px-\",\"rounded--32px-\",'border']}}"
> ```
> 
> 在微信开发者工具上运行正常，但是一旦点击 remote debug，微信 compile 后会报错：
> 
> ```
> message：Remote Debug Error: 1:836:unexpected character `\`
> ```
> 
> 不知道这里为啥要使用 `"` 然后再转义，如果都替换成 `'` 就没问题，好像微信 compile 的时候不让用 `\`

可以提供一个具体、完整、编译前的代码例子吗？

**Comment by tianzhich** [comment]
感谢及时回复，由于是公司代码，我简单摘取一个片段以及我的配置。使用 [uniapp vue3/vite](https://uniapp.dcloud.net.cn/quickstart-cli.html) 创建的模板

```html
<div class="flex flex-1 h-[1px] bg-content-quartenary opacity-10"></div>
```

```ts
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";
import { resolve } from "path";
import tailwindcss from "tailwindcss";
import nested from "tailwindcss/nesting";
import postcssPresetEnv from "postcss-preset-env";
import uniTailwind from "@uni-helper/vite-plugin-uni-tailwind";
import tailwindcssConfig from "./tailwind.config.ts";
import { uniPolyfill } from "./plugins/uni-polyfill";

// https://vitejs.dev/config/
export default defineConfig({
  css: {
    postcss: {
      plugins: [
        nested(),
        tailwindcss({
          config: tailwindcssConfig,
        }),
        postcssPresetEnv({
          stage: 3,
          features: { "custom-properties": { preserve: false } },
        }),
      ],
    },
  },
  plugins: [
    uni(),
    uniTailwind({
      /* options */
    }),
    uniPolyfill(),
  ],
  resolve: {
    alias: {
      "~": resolve(__dirname, "src"),
    },
  },
});
```

**Comment by tianzhich** [comment]
本质上还是微信的问题，开发者工具能正常解析 wxml 的转义字符 `\`，但是那边一旦 compile 以后就会报错。不过我不太确定的是这个 `\"` 是我们这边插件生成的还是 uniapp 那边，如果能把 `\"` 替换成 `'` 就 ok 了

**Comment by ModyQyW** [comment]
Thank you，我尽快看一下

**Comment by tianzhich** [comment]
我自己也排查了下，好像最终的 wxml 内容是 uniapp 生成的，这样的话可能得在那边看看了，但我也不是完全确定，也没找到类似 issue

```
class="{{['px-5','py-4',\"leading--32px-\",\"rounded--32px-\",'border']}}"
```

**Comment by ModyQyW** [comment]
> 应该和 :class 没关系，我发现如果使用的 `leading-[32px] rounded-[32px]` 这种，编译出来的就是：
> 
> ```
> class="{{['px-5','py-4',\"leading--32px-\",\"rounded--32px-\",'border']}}"
> ```
> 
> 在微信开发者工具上运行正常，但是一旦点击 remote debug，微信 compile 后会报错：
> 
> ```
> message：Remote Debug Error: 1:836:unexpected character `\`
> ```
> 
> 不知道这里为啥要使用 `"` 然后再转义，如果都替换成 `'` 就没问题，好像微信 compile 的时候不让用 `\`

我尝试使用项目 playground 复现，但仍然不能复现出这种编译结果。以下是我的尝试步骤：

1. 拉取项目

2. 安装依赖 `pnpm install`

3. 修改 `playground/src/pages/index/index.vue`

```vue
<script setup lang="ts">
import { ref } from "vue";
const title = ref("Hello");
</script>

<template>
  <view
    class="flex flex-col items-center justify-center leading-[32px] rounded-[32px]"
  >
    <image
      class="h-200rpx w-200rpx mt-200rpx mb-50rpx mx-auto"
      src="/static/logo.png"
    />
    <view class="flex justify-center">
      <text class="text-lg text-[#8f8f94]">{{ title }}</text>
    </view>
  </view>
</template>

```

4. 执行命令 `pnpm run build && cd playground && pnpm run dev:mp-weixin`

5. 查看编译结果 `dist/dev/mp-weixin/pages/index/index.wxml`，发现正常

```html
<view class="flex flex-col items-center justify-center leading--32px- rounded--32px-"><image class="h-200rpx w-200rpx mt-200rpx mb-50rpx mx-auto" src="{{a}}" /><view class="flex justify-center"><text class="text-lg text---h-8f8f94-">{{b}}</text></view></view>
```

我的环境信息：

```shell
  System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 99.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.local/state/fnm_multishells/60671_1730955282327/bin/node
    npm: 10.9.0 - ~/.local/state/fnm_multishells/60671_1730955282327/bin/npm
    pnpm: 9.12.3 - ~/.local/state/fnm_multishells/60671_1730955282327/bin/pnpm
    Watchman: 2024.11.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 130.0.6723.92
    Edge: 130.0.2849.68
    Safari: 18.1
```


不能复现，是我哪一步步骤错了吗？🤔

**Comment by ModyQyW** [comment]
我只能在使用 :class 时复现

**Comment by tianzhich** [comment]
babel 稍微有点复杂，我没继续研究下去，但问题就出在这里，你有时间的话可以看看～

**Comment by ModyQyW** [comment]
v0.15.2

**Comment by tianzhich** [comment]
感谢👍，其实我刚才也想这样修提个 PR，但是我担心这样会不会影响那些本来就是双引号包括的内容，正常来讲 babel 应该做了这样的判断（在我上面列的 issue 里），所以就没提。

还是很感谢帮忙，困扰了我一上午哈哈

**Comment by ModyQyW** [comment]
理论上不会有双引号包裹的内容，要是有就再处理吧
