### ISSUE TITLE
编译小红书小程序未生效

### ISSUE THREAD

**Issue by GL-28** [uni-helper/vite-plugin-uni-tailwind#39]
### 描述问题

使用uniappp-cli脚手架开发的小红书小程序, 编译到小程序编译器中 html的标签的class  w-[100rpx]未编译为w--100rpx-,
看了其他小程序端, 都是可以编译为w--100rpx-才生效

### 复现

将uniapp-vue3小程序编译到小红书小程序, 就可以复现了

### 系统信息

基础环境信息:
  - os: `macOS 14.0`
  - node: `18.20.2`
  - packageManager: `pnpm`

基础依赖信息:
  - vue: `3.5.8`
  - vite: `5.2.8`
  - @dcloudio/uni-app: `3.0.0-alpha-3090220231010001

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by ModyQyW** [comment]
久等了，已经发布v0.15.1修复这个问题
