### ISSUE TITLE
能否出一个完整对接tailwind步骤的教程

### ISSUE THREAD

**Issue by nadirvishun** [uni-helper/vite-plugin-uni-tailwind#40]
### 对问题的清晰和简明的描述

readme中只有关于本插件的介绍及配置，但是很多人并不清楚这个插件如何与tailwind关联，还提到了[playground](https://github.com/uni-helper/vite-plugin-uni-tailwind/tree/main/playground)这个示例，但是一眼看不出到底哪些文件进行了变更，需要挨个对比到底缺少了哪些组件，能否出一个一步步的操作教程呢？

### 推荐的解决方案

无

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
插件如何与 tailwind 关联，指的是什么？tailwindcss 的配置？

**Comment by nadirvishun** [comment]
是的，我只看过`tailwindcss`的基础文档，对整个集成流程还不是很熟悉。
我目前用uniapp最新版本测试遇到的一些问题：
- 还需要额外安装这些组件：`tailwind-extensions、autoprefixer、postcss、postcss-preset-env`，这些需要挨个对比出来。
- `vite.config.ts`中最后`import.meta.url`再`webstorm`中会标红提示` The import.meta meta-property is only allowed when the --module option is es2020, es2022, esnext, system, node16, or nodenext`，但测试不管也能正常运行
- `tsconfig.json`uniapp自带的与示例中的版本差别很大，我没有改动也可以运行，但是不确定是否有影响。
- 我看`tailwind`官方文档中还需要用`npx -i xxx -o xxx -watch`来监控自动编译，我以为也要配置相关的输入输出文件，但测试不需要配置也能自动编译。
- 我看还有人说要配置`rem`转`rpx`，不知道是否需要配置？

对新手来说比较需要一个完整的能按照一步步配置后就能正常运行的一个教程。

**Comment by ModyQyW** [comment]
我的想法和你的不太一样

1. 新手最好不要自己来配置这些，uniapp官方模板本身依赖和配置就很落后，很多东西需要改，用已经配置好的第三方模板对新手会更友好，不必耗费时间，先跑通再研究。

2. 插件不负责说明插件外的部分，除非插件外的部分也没说清楚。如果把tailwindcss配置也纳入到说明，还会有人需要postcss、uniapp、vite说明，插件做不到全包，还是建议自己去看相对应的文档。

**Comment by nadirvishun** [comment]
我搜索过uniapp对接tailwind的很多教程，但是各个教程内容都不一样，安装的依赖也不一样，有些也没说小程序的问题，所以很难一个个去测试，所以想找一个支持好的比较全面的教程。当然我也明白，如果能提供完整步骤是锦上添花的事情。

**Comment by nadirvishun** [comment]
这里总结下我安装了最新版的uniapp后的集成步骤：
1、安装依赖：`npm install -D tailwindcss tailwind-extensions postcss autoprefixer postcss-preset-env @uni-helper/vite-plugin-uni-tailwind`。
2、根目录下创建`tailwind.config.ts`文件，注意是`ts`类型的，内容可以直接复制示例中的。
3、修改根目录下的`vite.config.ts`文件，内容可以直接复制示例中的。
4、修改根目录下的`tsconfig.json`文件，内容可以直接复制示例中的。
5、根目录创建`styles`文件夹，将示例中的`preflight.css`和`tailwind.css`两个文件复制过来。
6、修改根目录下的`main.ts`文件，参考示例加入`import './styles/preflight.css'`和 `import './styles/tailwind.css';`的引用。

以上步骤完成后就可以正常使用`tailwindcss`了
